[package]
name = "pagefeed"
version = "0.2.0"
authors = ["Peter De Wachter <pdewacht@gmail.com>"]
license = "GPL-2.0+"
publish = false

[dependencies]
chrono = "^0.2.22"
fastcgi = "^1.0.0-beta"
hyper = "^0.9.5"
rss = "^0.3.1"
scoped_threadpool = "^0.1.7"
tiny-keccak = "^1.1.0"
regex = "0.1"

[dependencies.postgres]
version = "^0.13.1"
features = ["with-uuid", "with-chrono"]

[dependencies.uuid]
version = "^0.3.1"
features = ["v4"]
