[package]
name = "pagefeed"
version = "0.3.3"
authors = ["Peter De Wachter <pdewacht@gmail.com>"]
license = "GPL-2.0+"
publish = false

[dependencies]
chrono = "^0.4"
fastcgi = "^1.0.0-beta"
hyper = "^0.9.5"
rss = "^0.7"
scoped_threadpool = "^0.1.7"
tiny-keccak = "^1.1.0"
regex = "0.2"

[dependencies.postgres]
version = "^0.15"
features = ["with-uuid", "with-chrono"]

[dependencies.uuid]
version = "^0.5"
features = ["v4"]
